[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run prisma:generate && npm run migrate:deploy && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

