[build]
builder = "NIXPACKS"
installCommand = "npm install"
buildCommand = "npm run build"

[deploy]
# Явно запускаем через npm run, чтобы UI не перезаписывал команду
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

